    Array creation

In [3]:
# 1d array using numpy
import numpy as np

list = [1,2,3,4,5,6,7]

result = np.array(list)
print(result)


[1 2 3 4 5 6 7]


In [2]:
# 2d

list2 = [345,35,2,234,34,3,2]

result = np.array([list, list2])
print(result)

[[  1   2   3   4   5   6   7]
 [345  35   2 234  34   3   2]]


    Array manipulation

In [ ]:
import numpy as np

list3 = np.arange(10) # creating a 1 D array with 10 elements

print(list3)

[0 1 2 3 4 5 6 7 8 9]


In [17]:
list4 = list3.reshape(2,5) # reshaping a 1D array into 2D array example 2x5 or 5x2 try this
list4

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])