In [2]:
import numpy as np

a = np.array([1,2,3])
b = np.array([2,4,6])

result = np.add(a,b)
result

array([3, 6, 9])

In [3]:
import numpy as np

def add(x, y):
  return x + y

result = np.frompyfunc(add, 2, 1) # here 2 means 2 input arrays we can give as arguments and out put 1
result([12,3,4],[1,2,3])

array([13, 5, 7], dtype=object)

In [4]:
import numpy as np

a = np.array([1,2,3])
b = np.array([2,4,6])
c = np.array([5,6,7])

def multi(a, b, c):
    return a*b*c

result = np.frompyfunc(multi, 3, 1)

final = result(a,b,c)

print(final)

[10 48 126]


In [9]:
# string concatenate

import numpy as np

def str(a, b):
    return a + b

result = np.frompyfunc(str, 2, 1)

result("234342343", "dfgf23432")

'234342343dfgf23432'