In [3]:
# 1d array using numpy
import numpy as np

list = [1,2,3,4,5,6,7]

result = np.array(list)
print(result)


[1 2 3 4 5 6 7]


In [2]:
# 2d

list2 = [345,35,2,234,34,3,2]

result = np.array([list, list2])
print(result)

[[  1   2   3   4   5   6   7]
 [345  35   2 234  34   3   2]]
